#!/bin/sh

if git diff --cached --name-only | grep -q '^node_modules/'; then
  echo "🚫 node_modules is staged. Removing from commit..."
  git reset HEAD node_modules/
fi

if git diff --cached --name-only | grep -q '^frontend/node_modules/'; then
  echo "🚫 frontend/node_modules is staged. Removing from commit..."
  git reset HEAD frontend/node_modules/
fi

if git diff --cached --name-only | grep -q '^backend/node_modules/'; then
  echo "🚫 backend/node_modules is staged. Removing from commit..."
  git reset HEAD backend/node_modules/
fi

npx lint-staged
